# Generated by Django 5.1.7 on 2025-09-13 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TechCorp Solutions', max_length=100)),
                ('tagline', models.CharField(default='Delivering innovative technology solutions for modern businesses.', max_length=200)),
                ('email', models.EmailField(default='info@techcorpsolutions.com', max_length=254)),
                ('phone', models.CharField(default='(555) 123-4567', max_length=20)),
                ('address', models.TextField(default='123 Tech Street\nSan Francisco, CA 94105')),
                ('website', models.URLField(default='https://techcorpsolutions.com')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('email', 'Email'), ('phone', 'Phone'), ('website', 'Website')], max_length=20, unique=True)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (e.g., bi-facebook)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['display_order', 'platform'],
            },
        ),
    ]
